export const FETCH_STARTED = 'HOME/FETCH_STARTED';
export const FETCH_SUCCESS = 'HOME/FETCH_SUCCESS';
export const FETCH_FAILURE = 'HOME/FETCH_FAILURE';
export const ADD_ARTICLE = 'HOME/ADD_ARTICLE';