

export const ADD_COLLECTION = 'ADD_COLLECTION'
export const REMOVE_COLLECTION = 'REMOVE_COLLECTION'
export const ADD_NOTE = 'ADD_NOTE'
export const REMOVE_NOTE = 'REMOVE_NOTE'
export const CHANGE_TITLE = 'CHANGE_TITLE'
export const CHANGE_CONTENT = 'CHANGE_CONTENT'
export const TOGGLE_CLASS = 'TOGGLE_CLASS'
export const TOGGLE_ATTRUBUTE_STATUS = 'TOGGLE_ATTRUBUTE_STATUS'
export const FETCH_STARTED = 'FETCH_STARTED'
export const FETCH_SUCCESS = 'FETCH_SUCCESS'
export const FETCH_FAILURE = 'FETCH_FAILURE'
